# Generated by Django 4.2.16 on 2024-10-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fake_fqdn', models.CharField(max_length=200, unique=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('addressline', models.CharField(blank=True, max_length=200)),
                ('addressline2', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(default='customer', max_length=16)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='FR', max_length=2)),
                ('postalcode', models.CharField(blank=True, max_length=200)),
                ('streetnumber', models.CharField(blank=True, max_length=200)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this entity.', related_name='entity_permissions_set', to='auth.permission', verbose_name='entity permissions')),
            ],
            options={
                'db_table': 'supportaura_entity',
                'unique_together': {('label',)},
            },
        ),
    ]
