# Generated by Django 4.2.16 on 2024-10-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='supportaura_user',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='supportaura_ticket',
        ),
    ]
